#!/bin/bash

URL=http://requestb.in/11kvqg11

OPT_USER=${OPT_USER:-git}
TARGET_PATH=/home/$OPT_USER
APP_NAME=$(node -pe "'$1'.replace(/\.git$/, '').replace(/\//g, '-')")
TARGET_APP=$TARGET_PATH/$APP_NAME

echo "Creating app $TARGET_APP"
mkdir -p $TARGET_APP && cat | tar -x -C $TARGET_APP

[ -e $TARGET_APP/Dockerfile ] || exit 0

DOCKER_APP=$APP_NAME:$2

echo "Building docker image"
echo docker build -t $DOCKER_APP || exit 1
docker build -t $DOCKER_APP $TARGET_APP || exit 1

echo "Running container $DOCKER_APP"
docker run -d -P --name="$APP_NAME" $DOCKER_APP
